FROM openjdk:18-jdk AS build
VOLUME /tmp

# Install Python 3 and pip
RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

# Copy the JAR file into the container
COPY demo/target/demo-0.0.1-SNAPSHOT.jar demo-0.0.1-SNAPSHOT.jar

# Set the entrypoint to run the Java application
ENTRYPOINT ["java", "-jar", "/demo-0.0.1-SNAPSHOT.jar"]
