# Use an official Java runtime as a base image
FROM eclipse-temurin:17-jdk-alpine

# Install Python 3 and pip
RUN apk update && apk add --no-cache python3 py3-pip

# Set the working directory
WORKDIR /app

# Copy the JAR file into the container
COPY demo/target/demo-0.0.1-SNAPSHOT.jar demo-0.0.1-SNAPSHOT.jar

# Expose the application port (optional, change if needed)
EXPOSE 8080

# Run the JAR file
ENTRYPOINT ["java", "-jar", "/demo-0.0.1-SNAPSHOT.jar"]
