# Use a base image with OpenJDK and Debian/Ubuntu for package management
FROM openjdk:18-jdk-slim

# Set working directory
WORKDIR /app

# Install Python 3 and pip
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Create a volume for temporary files (optional, based on your needs)
VOLUME /tmp

# Copy the JAR file into the container
COPY demo/target/demo-0.0.1-SNAPSHOT.jar demo-0.0.1-SNAPSHOT.jar

# Run the JAR file
ENTRYPOINT ["java", "-jar", "demo-0.0.1-SNAPSHOT.jar"]