FROM openjdk:19-jdk AS build
WORKDIR /app

# Copy only necessary files first
COPY . .

# Ensure `mvnw` is executable
RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests

# Stage 2: Create the final Docker image
FROM openjdk:19-jdk
VOLUME /tmp

# Copy the JAR from the build stage
COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
EXPOSE 8080
