# Stage 1: Build the application
FROM maven:3.9.8-eclipse-temurin-17 AS builder
WORKDIR /app
COPY . .
RUN mvn dependency:go-offline -B

RUN mvn clean package -DskipTests

# Stage 2: Create the runtime image
FROM eclipse-temurin:18-jdk
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "-Dserver.address=0.0.0.0", "-Dserver.port=${PORT:-8080}", "app.jar"]
